### ISSUE TITLE
Errors testing development installation ( Liquid Exception: uninitialized constant Kramdown::Utils::OrderedHash in /_layouts/default.html)

### ISSUE THREAD

**Issue by liladude** [dnoneill/annotate#6]
Hi, I tried to install it locally but I run into several problems:
`Bundle >= 2 is required (not.1.3)`
Gemfile missing kramdown, so I manually added:
`gem "kramdown-parser-gfm"`
Now I run into a problem with Jekyll, failing with error
 `Liquid Exception: uninitialized constant Kramdown::Utils::OrderedHash in /_layouts/default.html`
I am working on Debian 10, freshly installed and updated Python3, Bundle, Ruby and Jekyll.

According to https://kramdown.gettalong.org/news.html OrderedHash has been removed in favor of Hash, if this could help.

Thanks

**Comment by dnoneill** [comment]
@liladude Have you tried using the vagrant machine installed in the repo? https://dnoneill.github.io/annotate/help/running-locally/. Also this code is very much out of date and not being kept up to date anymore. What are you looking at using this for?

**Comment by liladude** [comment]
@dnoneill I could not install the vagrant in my local environment. I need to install a local annotation server in order to host the annotations for the editorial workflow, which means that I wanted to see how it works in order to try developing a self hosted annotate and annotate for publishing. I will try to see if the vagrant work on an external server and I will report (or email you for some help!) 

Update: tried with Vagrant on new Virtual server, cannot ssh into vagrant... and vagrant up always timed out

**Comment by liladude** [comment]
Ok, I think I sorted it, somehow. Jekyll needs to be 3.8 and not >3.5, since 3.9 will break the code.
I added 
`gem "jekyll", "3.8"`
to Gemfile. Also, since in Gemfile.lock bundle=2.0, it complains, and you need to remove Gemfile.lock before install. I am still figuring out if I still need vyenv with Python 3, but since it is up and running, maybe not ;)
